/**
 * SURVIVORSHIP BIAS WARNING — read before trusting any backtest that uses these.
 *
 * These are the CURRENT index constituents. Backtesting them over history only
 * ever tests companies that survived and were promoted into the index; the ones
 * that were delisted, acquired, or demoted are absent. Every strategy scanned
 * across this universe will therefore look better than it would have been in
 * real time, and the effect grows the further back the window reaches.
 *
 * Fixing this properly needs point-in-time constituent lists (NSE publishes
 * index reconstitution history). Until then, treat cross-sectional scan results
 * as an upper bound, not an estimate.
 */
export const UNIVERSE_IS_SURVIVORSHIP_BIASED = true;

// Official Nifty 50 Index (Top 50 Blue Chip)
export const NIFTY_50_SYMBOLS = [
  "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BHARTIARTL.NS",
  "CIPLA.NS", "COALINDIA.NS", "DRREDDY.NS", "EICHERMOT.NS", "ETERNAL.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HINDALCO.NS",
  "HINDUNILVR.NS", "ICICIBANK.NS", "ITC.NS", "INFY.NS", "INDIGO.NS", "JSWSTEEL.NS", "JIOFIN.NS", "KOTAKBANK.NS", "LT.NS", "M&M.NS",
  "MARUTI.NS", "MAXHEALTH.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS", "SHRIRAMFIN.NS", "SBIN.NS",
  "SUNPHARMA.NS", "TCS.NS", "TATACONSUM.NS", "TMPV.NS", "TATASTEEL.NS", "TECHM.NS", "TITAN.NS", "TRENT.NS", "ULTRACEMCO.NS", "WIPRO.NS"
];

// Official Nifty 100 Index
export const NIFTY_100_SYMBOLS = [
  "ABB.NS", "ADANIENSOL.NS", "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "DMART.NS",
  "AXISBANK.NS", "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BAJAJHLDNG.NS", "BANKBARODA.NS", "BEL.NS", "BPCL.NS", "BHARTIARTL.NS", "BOSCHLTD.NS",
  "BRITANNIA.NS", "CGPOWER.NS", "CANBK.NS", "CHOLAFIN.NS", "CIPLA.NS", "COALINDIA.NS", "CUMMINSIND.NS", "DLF.NS", "DIVISLAB.NS", "DRREDDY.NS",
  "EICHERMOT.NS", "ETERNAL.NS", "GAIL.NS", "GODREJCP.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCAMC.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HINDALCO.NS",
  "HAL.NS", "HINDUNILVR.NS", "HINDZINC.NS", "HYUNDAI.NS", "ICICIBANK.NS", "ITC.NS", "INDHOTEL.NS", "IOC.NS", "IRFC.NS", "INFY.NS",
  "INDIGO.NS", "JSWSTEEL.NS", "JINDALSTEL.NS", "JIOFIN.NS", "KOTAKBANK.NS", "LTM.NS", "LT.NS", "LODHA.NS", "M&M.NS", "MARUTI.NS",
  "MAXHEALTH.NS", "MAZDOCK.NS", "MUTHOOTFIN.NS", "NTPC.NS", "NESTLEIND.NS", "ONGC.NS", "PIDILITIND.NS", "PFC.NS", "POWERGRID.NS", "PNB.NS",
  "RECLTD.NS", "RELIANCE.NS", "SBILIFE.NS", "MOTHERSON.NS", "SHREECEM.NS", "SHRIRAMFIN.NS", "ENRIN.NS", "SIEMENS.NS", "SOLARINDS.NS", "SBIN.NS",
  "SUNPHARMA.NS", "TVSMOTOR.NS", "TATACAP.NS", "TCS.NS", "TATACONSUM.NS", "TMCV.NS", "TMPV.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TECHM.NS",
  "TITAN.NS", "TORNTPHARM.NS", "TRENT.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UNITDSPR.NS", "VBL.NS", "VEDL.NS", "WIPRO.NS", "ZYDUSLIFE.NS"
];

// Official Nifty Midcap 150
export const NIFTY_MIDCAP_150_SYMBOLS = [
  "360ONE.NS", "3MINDIA.NS", "ACC.NS", "AIAENG.NS", "APLAPOLLO.NS", "AUBANK.NS", "AWL.NS", "ABBOTINDIA.NS", "ATGL.NS", "ABCAPITAL.NS",
  "AJANTPHARM.NS", "ALKEM.NS", "ANTHEM.NS", "APARINDS.NS", "APOLLOTYRE.NS", "ASHOKLEY.NS", "ASTRAL.NS", "AUROPHARMA.NS", "AIIL.NS", "BSE.NS",
  "BAJAJHFL.NS", "BALKRISIND.NS", "BANKINDIA.NS", "MAHABANK.NS", "BERGEPAINT.NS", "BDL.NS", "BHARATFORG.NS", "BHEL.NS", "BHARTIHEXA.NS", "GROWW.NS",
  "BIOCON.NS", "BLUESTARCO.NS", "CRISIL.NS", "COCHINSHIP.NS", "COFORGE.NS", "COLPAL.NS", "CONCOR.NS", "COROMANDEL.NS", "DABUR.NS", "DALBHARAT.NS",
  "DIXON.NS", "ENDURANCE.NS", "ESCORTS.NS", "EXIDEIND.NS", "NYKAA.NS", "FEDERALBNK.NS", "FORTIS.NS", "GVT&D.NS", "GMRAIRPORT.NS", "GICRE.NS",
  "GLAXO.NS", "GLENMARK.NS", "MEDANTA.NS", "GODFRYPHLP.NS", "GODREJIND.NS", "GODREJPROP.NS", "FLUOROCHEM.NS", "HDBFS.NS", "HAVELLS.NS", "HEROMOTOCO.NS",
  "HEXT.NS", "HINDPETRO.NS", "POWERINDIA.NS", "HONAUT.NS", "HUDCO.NS", "ICICIGI.NS", "ICICIAMC.NS", "ICICIPRULI.NS", "IDFCFIRSTB.NS", "ITCHOTELS.NS",
  "INDIANB.NS", "IRCTC.NS", "IREDA.NS", "INDUSTOWER.NS", "INDUSINDBK.NS", "NAUKRI.NS", "IPCALAB.NS", "JKCEMENT.NS", "JSWENERGY.NS", "JSWINFRA.NS",
  "JSL.NS", "JUBLFOOD.NS", "KPRMILL.NS", "KEI.NS", "KPITTECH.NS", "KALYANKJIL.NS", "LTF.NS", "LTTS.NS", "LGEINDIA.NS", "LICHSGFIN.NS",
  "LAURUSLABS.NS", "LENSKART.NS", "LICI.NS", "LINDEINDIA.NS", "LLOYDSME.NS", "LUPIN.NS", "MRF.NS", "M&MFIN.NS", "MANKIND.NS", "MARICO.NS",
  "MFSL.NS", "MOTILALOFS.NS", "MPHASIS.NS", "MCX.NS", "NHPC.NS", "NLCINDIA.NS", "NMDC.NS", "NTPCGREEN.NS", "NATIONALUM.NS", "NAM-INDIA.NS",
  "OBEROIRLTY.NS", "OIL.NS", "PAYTM.NS", "OFSS.NS", "POLICYBZR.NS", "PIIND.NS", "PAGEIND.NS", "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS",
  "PHOENIXLTD.NS", "POLYCAB.NS", "PREMIERENE.NS", "PRESTIGE.NS", "RADICO.NS", "RVNL.NS", "SBICARD.NS", "SJVN.NS", "SRF.NS", "SCHAEFFLER.NS",
  "SAIL.NS", "SUNDARMFIN.NS", "SUPREMEIND.NS", "SUZLON.NS", "SWIGGY.NS", "TATACOMM.NS", "TATAELXSI.NS", "TATAINVEST.NS", "NIACL.NS", "THERMAX.NS",
  "TORNTPOWER.NS", "TIINDIA.NS", "UNOMINDA.NS", "UPL.NS", "UBL.NS", "VMM.NS", "IDEA.NS", "VOLTAS.NS", "WAAREEENER.NS", "YESBANK.NS"
];

// Official Nifty Smallcap 250
export const NIFTY_SMALLCAP_250_SYMBOLS = [
  "ACMESOLAR.NS", "AADHARHFC.NS", "AARTIIND.NS", "AAVAS.NS", "ACE.NS", "ACUTAAS.NS", "ABFRL.NS", "ABLBL.NS", "ABREL.NS", "ABSLAMC.NS",
  "CPPLUS.NS", "AEGISLOG.NS", "AEGISVOPAK.NS", "AFCONS.NS", "AFFLE.NS", "ABDL.NS", "ARE&M.NS", "AMBER.NS", "ANANDRATHI.NS", "ANANTRAJ.NS",
  "ANGELONE.NS", "ANURAS.NS", "APTUS.NS", "ASAHIINDIA.NS", "ASTERDM.NS", "ATHERENERG.NS", "ATUL.NS", "BEML.NS", "BLS.NS", "BALRAMCHIN.NS",
  "BANDHANBNK.NS", "BATAINDIA.NS", "BAYERCROP.NS", "BELRISE.NS", "BIKAJI.NS", "BSOFT.NS", "BLUEDART.NS", "BLUEJET.NS", "BBTC.NS", "FIRSTCRY.NS",
  "BRIGADE.NS", "MAPMYINDIA.NS", "CCL.NS", "CESC.NS", "CIEINDIA.NS", "CANFINHOME.NS", "CANHLIFE.NS", "CAPLIPOINT.NS", "CGCL.NS", "CARBORUNIV.NS",
  "CARTRADE.NS", "CASTROLIND.NS", "CEATLTD.NS", "CEMPRO.NS", "CENTRALBK.NS", "CDSL.NS", "CHALET.NS", "CHAMBLFERT.NS", "CHENNPETRO.NS", "CHOICEIN.NS",
  "CHOLAHLDNG.NS", "CUB.NS", "CLEAN.NS", "COHANCE.NS", "CAMS.NS", "CONCORDBIO.NS", "CRAFTSMAN.NS", "CREDITACC.NS", "CROMPTON.NS", "CYIENT.NS",
  "DCMSHRIRAM.NS", "DOMS.NS", "DATAPATTNS.NS", "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DEVYANI.NS", "LALPATHLAB.NS", "EIDPARRY.NS", "EIHOTEL.NS",
  "ELECON.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "EMCURE.NS", "EMMVEE.NS", "ENGINERSIN.NS", "ERIS.NS", "FACT.NS", "FINCABLES.NS", "FSL.NS",
  "FIVESTAR.NS", "FORCEMOT.NS", "GABRIEL.NS", "GALLANTT.NS", "GRSE.NS", "GILLETTE.NS", "GLAND.NS", "GODIGIT.NS", "GPIL.NS", "GRANULES.NS",
  "GRAPHITE.NS", "GRAVITA.NS", "GESHIP.NS", "GMDCLTD.NS", "HEG.NS", "HBLENGINE.NS", "HFCL.NS", "HSCL.NS", "HINDCOPPER.NS", "HOMEFIRST.NS",
  "HONASA.NS", "IDBI.NS", "IFCI.NS", "IIFL.NS", "IRB.NS", "IRCON.NS", "ITI.NS", "INDGN.NS", "INDIACEM.NS", "INDIAMART.NS",
  "IEX.NS", "IOB.NS", "IGL.NS", "INOXWIND.NS", "INTELLECT.NS", "IGIL.NS", "IKS.NS", "JBCHEPHARM.NS", "JBMA.NS", "JKTYRE.NS",
  "JMFINANCIL.NS", "JSWCEMENT.NS", "JSWDULUX.NS", "JAINREC.NS", "JPPOWER.NS", "J&KBANK.NS", "JINDALSAW.NS", "JUBLINGREA.NS", "JUBLPHARMA.NS", "JWL.NS",
  "JYOTICNC.NS", "KAJARIACER.NS", "KPIL.NS", "KARURVYSYA.NS", "KAYNES.NS", "KEC.NS", "KFINTECH.NS", "KIRLOSENG.NS", "KIMS.NS", "LTFOODS.NS",
  "LATENTVIEW.NS", "THELEELA.NS", "LEMONTREE.NS", "MMTC.NS", "MGL.NS", "MANAPPURAM.NS", "MRPL.NS", "MEESHO.NS", "MINDACORP.NS", "MSUMI.NS",
  "NATCOPHARM.NS", "NBCC.NS", "NCC.NS", "NSLNISP.NS", "NH.NS", "NAVA.NS", "NAVINFLUOR.NS", "NETWEB.NS", "NEULANDLAB.NS", "NEWGEN.NS",
  "NIVABUPA.NS", "NUVAMA.NS", "NUVOCO.NS", "OLAELEC.NS", "OLECTRA.NS", "ONESOURCE.NS", "PCBL.NS", "PGEL.NS", "PNBHOUSING.NS", "PTCIL.NS",
  "PVRINOX.NS", "PARADEEP.NS", "PFIZER.NS", "PWL.NS", "PINELABS.NS", "PIRAMALFIN.NS", "PPLPHARMA.NS", "POLYMED.NS", "POONAWALLA.NS", "RRKABEL.NS",
  "RBLBANK.NS", "RHIM.NS", "RITES.NS", "RAILTEL.NS", "RAINBOW.NS", "RKFORGE.NS", "REDINGTON.NS", "RPOWER.NS", "SBFC.NS", "SAGILITY.NS",
  "SAILIFE.NS", "SAMMAANCAP.NS", "SAPPHIRE.NS", "SARDAEN.NS", "SAREGAMA.NS", "SCHNEIDER.NS", "SCI.NS", "SHYAMMETL.NS", "SIGNATURE.NS", "SOBHA.NS",
  "SONACOMS.NS", "SONATSOFTW.NS", "STARHEALTH.NS", "SUMICHEM.NS", "SUNTV.NS", "SPLPETRO.NS", "SWANCORP.NS", "SYNGENE.NS", "SYRMA.NS", "TBOTEK.NS",
  "TATACHEM.NS", "TATATECH.NS", "TTML.NS", "TECHNOE.NS", "TEGA.NS", "TEJASNET.NS", "TENNIND.NS", "RAMCOCEM.NS", "TIMKEN.NS", "TITAGARH.NS",
  "TARIL.NS", "TRAVELFOOD.NS", "TRIDENT.NS", "TRITURBINE.NS", "UCOBANK.NS", "UTIAMC.NS", "URBANCO.NS", "USHAMART.NS", "VTL.NS", "VIJAYA.NS",
  "WELCORP.NS", "WELSPUNLIV.NS", "WHIRLPOOL.NS", "WOCKPHARMA.NS", "ZFCVINDIA.NS", "ZEEL.NS", "ZENTEC.NS", "ZENSARTECH.NS", "ZYDUSWELL.NS", "ECLERX.NS"
];

// Full Official Nifty 500
export const NIFTY_500_SYMBOLS = [...NIFTY_100_SYMBOLS, ...NIFTY_MIDCAP_150_SYMBOLS, ...NIFTY_SMALLCAP_250_SYMBOLS];
